### ISSUE TITLE
 No module named 'object_detection'

### ISSUE THREAD

**Issue by menirite** [omarabid59/TensorflowDeepSortTracking#1]
E:\TensorflowDeepSortTracking-master>python object_tracking.py
Traceback (most recent call last):
  File "object_tracking.py", line 6, in <module>
    from utilities import helper
  File "E:\TensorflowDeepSortTracking-master\utilities\helper.py", line 2, in <module>
    from object_detection.utils import visualization_utils as vis_util
ModuleNotFoundError: No module named 'object_detection'

**Comment by omarabid59** [comment]
Please see the [Tensorflow Guide](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md).  You need to compile the protoc libraries and add libraries to path. 

# From tensorflow/models/research/
protoc object_detection/protos/*.proto --python_out=.
export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
