### ISSUE TITLE
AssertionError: Could not open Webcam.

### ISSUE THREAD

**Issue by XNKT** [omarabid59/TensorflowDeepSortTracking#3]
assert cap.isOpened() == True, 'Could not open Webcam.'

**Comment by omarabid59** [comment]
Please make sure you have a Webcam connected.

**Comment by XNKT** [comment]
thank you ！
I have solved the problem




------------------ 原始邮件 ------------------
发件人: "Omar Abid"<notifications@github.com>;
发送时间: 2018年11月21日(星期三) 凌晨2:58
收件人: "omarabid59/TensorflowDeepSortTracking"<TensorflowDeepSortTracking@noreply.github.com>;
抄送: "薛宁"<xue666ning@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [omarabid59/TensorflowDeepSortTracking] AssertionError: Could notopen Webcam. (#3)




Please make sure you have a Webcam connected.

**Comment by abaybektursun** [comment]
lol this cracked me up
